name: Build

on:
  pull_request:
    types:
      - opened
      - reopened
  push:
    branches-ignore:
      - 'master'

jobs:
  build-and-test:
    runs-on: windows-latest
    
    strategy:
      matrix:
        dotnet-version: [ '4.5.2' ]
    
    steps:
      - uses: actions/checkout@v3
      - name: Install .NET Framework 4.5.2
        run: |
          Invoke-WebRequest https://download.microsoft.com/download/4/3/B/43B61315-B2CE-4F5B-9E32-34CCA07B2F0E/NDP452-KB2901951-x86-x64-DevPack.exe
          .\NDP452-KB2901951-x86-x64-DevPack.exe /q
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test BitPayUnitTest --no-restore --verbosity n